# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANDs_of_ORs', models.CharField(max_length=10000)),
                ('ORs_of_ANDs', models.CharField(max_length=10000)),
                ('custom', models.CharField(max_length=10000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
