# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobList', '0002_userlogic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogic',
            name='ANDs_of_ORs',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='userlogic',
            name='ORs_of_ANDs',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='userlogic',
            name='custom',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
