# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobList', '0003_auto_20161209_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('jobs', models.ManyToManyField(to='JobList.Job')),
            ],
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='jobs',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
