# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobList', '0004_auto_20170107_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPledgeFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkerFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive', models.IntegerField(null=True)),
                ('inactive_unit', models.CharField(default='', max_length=4)),
                ('updated', models.IntegerField(null=True)),
                ('updated_unit', models.CharField(default='', max_length=4)),
                ('completed_fewer', models.IntegerField(null=True)),
                ('failed_to_complete', models.IntegerField(null=True)),
                ('completed_percent', models.IntegerField(null=True)),
                ('better_than_complete_fail_ratio', models.FloatField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
