# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobList', '0005_userpledgefilter_userworkerfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkerfilter',
            name='completed_percent',
            field=models.FloatField(null=True),
        ),
    ]
