# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobList', '0006_auto_20170112_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pledgers',
            field=models.ManyToManyField(related_name='pledgers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='workers',
            field=models.ManyToManyField(related_name='workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
