# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobList', '0007_auto_20170113_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='pledgers',
            field=models.ManyToManyField(related_name='pledging', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='workers',
            field=models.ManyToManyField(related_name='working', to=settings.AUTH_USER_MODEL),
        ),
    ]
