
URLS = {
    'robots': 'robots.txt',
    'password_reset': 'password_reset',
    'done': 'done',
    'uidb66_regex': '(?P<uidb64>[0-9A-Za-z_\-]+)',
    'token_regex': '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})',
    'account': 'account',
    'privacy': 'privacy',
    'create': 'create',
    'update': 'update', 
    'pledge': 'pledge',
    'pay': 'pay', 
    'work': 'work',
    'password_reset': 'password_reset',
    'reset': 'reset',
    'admin': 'admin',
    'job': 'job',
    'about': 'about',
    'contact': 'contact',
    'home': 'home',
    'search-users': 'search-users',
    'see-more-users': 'see-more-users',
    'job_random_string_regex': '(?P<job_random_string>[a-zA-Z0-9]+)',
    'username_regex': '(?P<username>[a-zA-Z0-9_]+)',
    'terms_of_service': 'terms_of_service',
    'get-jobs': 'get-jobs',
    'get-total-jobs': 'get-total-jobs',
    'sort': 'sort',
    'stripe': 'stripe',
    'log-in': 'log-in',
    'sign-out': 'sign-out',
    'account': 'account',
    'search-users': 'search-users',
    'see-more-users': 'see-more-users',
};