
URLS = {
    'robots': 'robots.txt',
    'password_reset': 'password_reset',
    'done': 'done',
    'uidb66_regex': '(?P<uidb64>[0-9A-Za-z_\-]+)',
    'token_regex': '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})',
    'account': 'account',
    'accounts' : 'accounts',
    'privacy': 'privacy',
    'create': 'create',
    'update': 'update',
    'delete': 'delete',
    'images': 'images',
    'pledge': 'pledge',
    'misc-pay': 'misc-pay',
    'stripe-pay': 'stripe-pay',
    'confirm-pay' : 'confirm-pay',
    'work': 'work',
    'finish': 'finish',
    'password_reset': 'password_reset',
    'reset': 'reset',
    'admin': 'admin',
    'privacy': 'privacy',
    'job': 'job',
    'user': 'user',
    'moderate': 'moderate',
    'ban-user': 'ban-user',
    'received-payment': 'received-payment',
    'pledge-history': 'pledge-history',
    'work-history': 'work-history',
    'about': 'about',
    'contact': 'contact',
    'home': 'home',
    'search-user': 'search-user',
    'see-more-users': 'see-more-users',
    'job_random_string_regex': '(?P<job_random_string>[a-zA-Z0-9]+)',
    'username_regex': '(?P<username>[a-zA-Z0-9_]+)',
    'jobuser_random_string_regex': '(?P<jobuser_random_string>[a-zA-Z0-9]+)',
    'update_random_string_regex': '(?P<update_random_string>[a-zA-Z0-9]+)',
    'terms_of_service': 'terms_of_service',
    'get-jobs': 'get-jobs',
    'get-total-jobs': 'get-total-jobs',
    'sort': 'sort',
    'stripe': 'stripe',
    'log-in': 'log-in',
    'sign-out': 'sign-out',
    'account': 'account',
    'edit-profile': 'edit-profile',
    'search-users': 'search-users',
    'see-more-users': 'see-more-users',
};
