# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('creation_date', models.DateField()),
                ('last_time_money_pledged', models.DateField()),
                ('last_time_worked_on', models.DateField()),
                ('money_pledged', models.FloatField()),
                ('num_people_doing_job', models.FloatField()),
            ],
        ),
    ]
