# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobList_Pledge', '0002_auto_20160827_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_name',
            new_name='name',
        ),
    ]
