# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobList_Pledge', '0003_auto_20160827_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='last_time_money_pledged',
        ),
    ]
