# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobList_Pledge', '0004_remove_job_last_time_money_pledged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='creation_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_time_worked_on',
            field=models.CharField(max_length=100),
        ),
    ]
