# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobList_Pledge', '0005_auto_20160827_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_time_worked_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='money_pledged',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='job',
            name='num_people_doing_job',
            field=models.IntegerField(default='0'),
        ),
    ]
