# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobList_Pledge', '0008_auto_20161009_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
