# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobList_Pledge', '0009_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
