# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobList_Pledge', '0010_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.FloatField(default='0.0'),
        ),
    ]
