# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobList_Pledge', '0011_auto_20161104_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=30)),
                ('jobs', models.ManyToManyField(to='jobList_Pledge.Job')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='jobs',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
