# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-20 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complaint', models.BooleanField(default=False)),
                ('has_been_nullified', models.BooleanField(default=False)),
                ('commented', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('comment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobuser.Comment')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('is_pledge', models.BooleanField(default=False)),
                ('pledge', models.FloatField(default=0.0)),
                ('is_payment', models.BooleanField(default=False)),
                ('payment', models.FloatField(default=0.0)),
                ('is_update', models.BooleanField(default=False)),
                ('is_comment', models.BooleanField(default=False)),
                ('is_new_worker', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('date_viewed', models.DateTimeField(blank=True, null=True)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobuser.Comment')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
                ('notifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PledgeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pledged', models.DateTimeField(auto_now_add=True)),
                ('amount_pledged', models.IntegerField(blank=True, editable=False, null=True)),
                ('amount_paid', models.IntegerField(blank=True, default=0, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
                ('pledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('amount_of_money_asking_for', models.IntegerField(blank=True, null=True)),
                ('total_comments', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkJobUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=10000)),
                ('has_active_complaint', models.BooleanField(default=False)),
                ('num_complaints', models.IntegerField(default=0)),
                ('workjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobuser.WorkJob')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobuser.WorkJobUpdate'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='workJobUpdate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobuser.WorkJobUpdate'),
        ),
        migrations.AddField(
            model_name='comment',
            name='update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobuser.WorkJobUpdate'),
        ),
    ]
