# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_money_request', models.BooleanField(default=False)),
                ('money_request', models.IntegerField()),
                ('is_update', models.BooleanField(default=False)),
                ('is_comment', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('date_viewed', models.DateTimeField(blank=True, null=True)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobuser.Comment')),
                ('update', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobuser.WorkJobUpdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_update', models.BooleanField(default=False)),
                ('is_comment', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('date_viewed', models.DateTimeField(blank=True, null=True)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobuser.Comment')),
                ('update', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobuser.WorkJobUpdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
