# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_imageupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobuser', '0002_auto_20170524_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, editable=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobuser.JobUser')),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, editable=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobuser.JobUser')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobuser.JobUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='pledgejob',
            name='job',
        ),
        migrations.RemoveField(
            model_name='pledgejob',
            name='pledger',
        ),
        migrations.RemoveField(
            model_name='workjob',
            name='job',
        ),
        migrations.RemoveField(
            model_name='workjob',
            name='worker',
        ),
        migrations.RenameField(
            model_name='update',
            old_name='updated',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='job',
        ),
        migrations.RemoveField(
            model_name='update',
            name='job',
        ),
        migrations.RemoveField(
            model_name='update',
            name='user',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobuser.Update'),
        ),
        migrations.AddField(
            model_name='update',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='update',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='PledgeJob',
        ),
        migrations.DeleteModel(
            name='WorkJob',
        ),
        migrations.AddField(
            model_name='finish',
            name='jobuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobuser.JobUser'),
        ),
        migrations.AddField(
            model_name='update',
            name='jobuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobuser.JobUser'),
            preserve_default=False,
        ),
    ]
