# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0003_auto_20170309_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgenotification',
            name='money_request',
            field=models.IntegerField(null=True),
        ),
    ]
