# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0003_auto_20170610_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='comment',
            new_name='description',
        ),
    ]
