# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobuser', '0004_auto_20170610_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
