# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0005_pay_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobuser',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
