# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0006_jobuser_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
