# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0007_auto_20170613_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='title',
            new_name='type',
        ),
    ]
