# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0007_imageupload_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
