# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0008_auto_20170613_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='type',
            new_name='title',
        ),
    ]
