# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0009_auto_20170407_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='super_comment',
        ),
    ]
