# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0010_remove_jobuser_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobuser',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
    ]
