# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0011_jobuser_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
