# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-14 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0012_auto_20170702_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobuser',
            name='amount_pledged',
            field=models.FloatField(default=0.0),
        ),
    ]
