# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0015_auto_20170802_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
