# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0016_auto_20170814_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobuser',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='jobuser',
            name='amount_pledged',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pay',
            name='amount',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
