# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobuser', '0017_auto_20170815_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='update',
        ),
        migrations.RemoveField(
            model_name='update',
            name='jobuser',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
