# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobuser', '0010_auto_20180116_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('random_string', models.CharField(default='', max_length=100)),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobuser.JobUser')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('random_string', models.CharField(default='', max_length=100)),
                ('jobuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobuser.JobUser')),
            ],
        ),
    ]
