# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='random_string',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
