# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('super_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='PledgeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pledged', models.DateTimeField(auto_now_add=True)),
                ('amount_pledged', models.IntegerField(blank=True, editable=False, null=True)),
                ('amount_paid', models.IntegerField(blank=True, default=0, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
                ('pledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('date_read', models.DateTimeField(blank=True, editable=False, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('PU', 'Pledge Job Update'), ('WU', 'Work Job Update'), ('CO', 'Comment'), ('MO', 'Asking For Money'), ('ME', 'Message')], max_length=2)),
                ('comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Comment')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserMessage')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=10000)),
                ('city', models.CharField(blank=True, max_length=1000)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('filter_is_public', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('amount_of_money_asking_for', models.IntegerField(blank=True, editable=False, null=True)),
                ('total_comments', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkJobUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=10000)),
                ('has_active_complaint', models.BooleanField(default=False)),
                ('num_complaints', models.IntegerField(default=0)),
                ('workjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.WorkJob')),
            ],
        ),
        migrations.AddField(
            model_name='usernotification',
            name='pledge_job_update',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pledge_job_update', to='user.WorkJobUpdate'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='work_job_update',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_job_update', to='user.WorkJobUpdate'),
        ),
        migrations.AddField(
            model_name='comment',
            name='workJobUpdate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.WorkJobUpdate'),
        ),
    ]
