# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('date_viewed', models.DateTimeField(blank=True, null=True)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dependent', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=10000)),
                ('public_first_name', models.BooleanField(default=False)),
                ('public_last_name', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=1000)),
                ('public_city', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('public_state', models.BooleanField(default=False)),
                ('public_filter', models.BooleanField(default=False)),
                ('dependent_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_on', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
