# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='filter_is_public',
            field=models.BooleanField(default=False),
        ),
    ]
