# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='userB',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messagesB', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='userA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagesA', to=settings.AUTH_USER_MODEL),
        ),
    ]
