# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='workJobUpdate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.WorkJobUpdate'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
