# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170223_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='twoUsers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Messages'),
            preserve_default=False,
        ),
    ]
