# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
