# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usermessage_twousers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='receiver',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='sender',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
