# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='Email: ', max_length=10000),
        ),
    ]
