# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170227_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='most_recent_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
