# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_messages_most_recent_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dependent_on',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_dependent',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='public_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='public_filter',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='public_first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='public_last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='public_state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='random_string',
            field=models.CharField(default='', max_length=20),
        ),
    ]
