# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 22:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20170825_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Alphabetic characters only')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Alphabetic characters only')]),
        ),
    ]
