# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20170825_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='job',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
