# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20170912_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterpledges',
            name='paid_at_least_n_amount_in_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='filterpledges',
            name='paid_at_least_n_percent_of_pledges',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='filterpledges',
            name='paid_at_least_n_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
