# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_filterworkers_not_been_active_in_the_last_n_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterpledges',
            name='paid_at_least_n_percent_of_pledges',
        ),
    ]
