# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_filterpledges_paid_at_least_n_percent_of_pledges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterpledges',
            name='user',
        ),
        migrations.RemoveField(
            model_name='filterworkers',
            name='user',
        ),
        migrations.DeleteModel(
            name='FilterPledges',
        ),
        migrations.DeleteModel(
            name='FilterWorkers',
        ),
    ]
