# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-20 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_finished', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('num_people_doing_job', models.IntegerField(default=0)),
                ('money_pledged', models.FloatField(default=0.0)),
                ('money_paid', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('random_string', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('jobs', models.ManyToManyField(to='job.Job')),
            ],
        ),
    ]
