# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_time_worked_on', models.DateTimeField(auto_now_add=True)),
                ('money_pledged', models.FloatField(default='0.0')),
                ('num_people_doing_job', models.IntegerField(default='0')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('description', models.CharField(default='', max_length=10000)),
                ('pledgers', models.ManyToManyField(related_name='pledging', to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(related_name='working', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('jobs', models.ManyToManyField(to='job.Job')),
            ],
        ),
        migrations.CreateModel(
            name='UserLogic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANDs_of_ORs', models.CharField(default='', max_length=10000)),
                ('ORs_of_ANDs', models.CharField(default='', max_length=10000)),
                ('custom', models.CharField(default='', max_length=10000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPledgeFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkerFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive', models.IntegerField(null=True)),
                ('inactive_unit', models.CharField(default='', max_length=4)),
                ('updated', models.IntegerField(null=True)),
                ('updated_unit', models.CharField(default='', max_length=4)),
                ('completed_fewer', models.IntegerField(null=True)),
                ('failed_to_complete', models.IntegerField(null=True)),
                ('completed_percent', models.FloatField(null=True)),
                ('better_than_complete_fail_ratio', models.FloatField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
