# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 19:04
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\s]+$', 'Alphanumeric characters only')])),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('pledged', models.PositiveIntegerField(default=0)),
                ('paid', models.PositiveIntegerField(default=0)),
                ('workers', models.PositiveIntegerField(default=0)),
                ('finished', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('random_string', models.CharField(default='', max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\s]+$', 'Alphanumeric characters only')])),
                ('jobs', models.ManyToManyField(to='job.Job')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Job'),
        ),
    ]
