# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
