# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 19:52
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpledgefilter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userworkerfilter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='job',
            name='main_editors',
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='UserLogic',
        ),
        migrations.DeleteModel(
            name='UserPledgeFilter',
        ),
        migrations.DeleteModel(
            name='UserWorkerFilter',
        ),
    ]
