# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_finished',
            field=models.BooleanField(default=True),
        ),
    ]
