# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20170313_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpledgefilter',
            name='averaged',
        ),
        migrations.RemoveField(
            model_name='userpledgefilter',
            name='failed_to_pay',
        ),
        migrations.AddField(
            model_name='userpledgefilter',
            name='total_amount_paid',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='UserLogic',
        ),
    ]
