# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20170503_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
