# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20170523_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
