# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20170414_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpledgefilter',
            name='inactive_unit',
        ),
        migrations.RemoveField(
            model_name='userworkerfilter',
            name='inactive_unit',
        ),
        migrations.RemoveField(
            model_name='userworkerfilter',
            name='updated_unit',
        ),
    ]
