# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20170123_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='BlogContent'),
        ),
    ]
