# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
            ],
        ),
    ]
