# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20170414_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpledgefilter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userworkerfilter',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPledgeFilter',
        ),
        migrations.DeleteModel(
            name='UserWorkerFilter',
        ),
    ]
