# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20170124_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpledgefilter',
            name='averaged',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userpledgefilter',
            name='failed_to_pay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userpledgefilter',
            name='inactive',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userpledgefilter',
            name='inactive_unit',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='userpledgefilter',
            name='paid_x_times',
            field=models.IntegerField(null=True),
        ),
    ]
