# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_imageupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='job',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
