# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20170125_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpledgefilter',
            name='inactive_unit',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='userworkerfilter',
            name='inactive_unit',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='userworkerfilter',
            name='updated_unit',
            field=models.CharField(default='', max_length=5),
        ),
    ]
