# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20170421_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='main_editors',
        ),
    ]
