# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20170612_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageUpload',
            new_name='Image',
        ),
    ]
