# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20170715_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='money_paid',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='money_pledged',
            new_name='pledged',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='num_workers',
            new_name='workers',
        ),
        migrations.AddField(
            model_name='job',
            name='finished',
            field=models.IntegerField(default=0),
        ),
    ]
