# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20170125_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userworkerfilter',
            old_name='better_than_complete_fail_ratio',
            new_name='completed_ratio',
        ),
    ]
