# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20170125_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkerfilter',
            name='completed_fewer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userworkerfilter',
            name='completed_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userworkerfilter',
            name='completed_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userworkerfilter',
            name='failed_to_complete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userworkerfilter',
            name='inactive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userworkerfilter',
            name='updated',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
